# Global configuration
baseurl: "/blog"
url: "http://skiel.pro"
author: Tina
timezone: Europe/Paris
permalink: :title:output_ext
google_analytics: UA-115802190-1

# Vars
title: "8bit Prince: Tina's blog // Code and baguettes"
email: skielred@gmail.com
description: >-
    A personal blog maintained by Tina, also known as Shookaite or skielred. About rhythm games, programming and Linux.
twitter: Shookaite
github:  skielred
discord: Tina#0573

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - README
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - new_post.sh
